# Generated by Django 5.1.3 on 2024-11-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='tiempo_notificacion',
            field=models.CharField(choices=[('24h', '24 horas antes'), ('1h', '1 hora antes'), ('15m', '15 minutos antes'), ('ahora', 'Al instante')], default='NOW', max_length=5),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='destinatario',
            field=models.EmailField(max_length=254),
        ),
    ]
