# Generated by Django 5.1.3 on 2024-11-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevo_evento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='asignado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
